# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ExampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleApp
  #  pod 'NAOSDKProvider', :path => '../'
  pod 'NAOSwiftProvider', :git => 'https://bitbucket.org/polestarusa/naoswiftprovider.git', :tag => '1.3.0'

end
